# Generated by Django 2.0.9 on 2019-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('customer_fullname', models.CharField(max_length=60)),
                ('services', models.CharField(choices=[('1', 'Usluga 1'), ('2', 'Usluga 2'), ('3', 'Usluga 3')], max_length=1)),
                ('drawing_id', models.IntegerField()),
                ('size', models.CharField(choices=[('1', 'Maly'), ('2', 'Sredni'), ('3', 'Duzy')], max_length=1)),
                ('customer', models.CharField(choices=[('1', 'Klient nr 1'), ('2', 'Klient nr 2'), ('3', 'Klient nr 3')], max_length=5)),
                ('receiver', models.CharField(choices=[('1', 'Klient nr 1'), ('2', 'Klient nr 2'), ('3', 'Klient nr 3')], max_length=5)),
                ('price', models.IntegerField()),
                ('term_date', models.DateTimeField()),
                ('add_date', models.DateTimeField()),
                ('order_code', models.IntegerField()),
                ('zamzap', models.CharField(choices=[('1', 'ZAMOWIENIE'), ('2', 'ZAP')], max_length=1)),
                ('copy_id', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
            ],
        ),
    ]
